/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IWrapperInterface extends utils.Interface {
  contractName: "IWrapper";
  functions: {
    "getOrgaisationWalletAddess(uint256)": FunctionFragment;
    "getOrganisationFee(uint256)": FunctionFragment;
    "getProtocolFee()": FunctionFragment;
    "getProtocolWalletAddress()": FunctionFragment;
    "getTokenRewardsCalculationAddress()": FunctionFragment;
    "getTreasuryAddress(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getOrgaisationWalletAddess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganisationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolWalletAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenRewardsCalculationAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryAddress",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOrgaisationWalletAddess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganisationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenRewardsCalculationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IWrapper extends BaseContract {
  contractName: "IWrapper";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getOrgaisationWalletAddess(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getOrganisationFee(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProtocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getProtocolWalletAddress(overrides?: CallOverrides): Promise<[string]>;

    getTokenRewardsCalculationAddress(
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTreasuryAddress(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getOrgaisationWalletAddess(
    organisationID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getOrganisationFee(
    organisationID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  getProtocolWalletAddress(overrides?: CallOverrides): Promise<string>;

  getTokenRewardsCalculationAddress(overrides?: CallOverrides): Promise<string>;

  getTreasuryAddress(
    organisationID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getOrgaisationWalletAddess(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrganisationFee(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    getProtocolWalletAddress(overrides?: CallOverrides): Promise<string>;

    getTokenRewardsCalculationAddress(
      overrides?: CallOverrides
    ): Promise<string>;

    getTreasuryAddress(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getOrgaisationWalletAddess(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrganisationFee(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    getProtocolWalletAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenRewardsCalculationAddress(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTreasuryAddress(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getOrgaisationWalletAddess(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrganisationFee(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProtocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProtocolWalletAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenRewardsCalculationAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTreasuryAddress(
      organisationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
